Beautify code

diff --git a/bin/kiss b/bin/kiss
--- a/bin/kiss
+++ b/bin/kiss
@@ -2,62 +2,65 @@
 if [[ "$PROJECT" ]]; then
   cd $HOME/$PROJECT
 else
-  if [[ "$1" ]]; then
-    name=`basename $1`
-    if [[ -d "$HOME/$name" ]]; then
-      if [[ "$bash_interactive" ]]; then
-        if [[ "$PROJECT" == "$name" ]]; then
-            echo Error: already in $PROJECT...
-            return
-        fi
-
-        oldpath=`pwd`
-        cd $HOME/$name
-        ci_pid=$!
-
-        PROJECT=$name \
-        PROJECT_DIR=$HOME/$PROJECT \
-        APP_DIR=$PROJECT_DIR/app \
-        HTML_DIR=$PROJECT_DIR/html \
-        CONFIG_DIR=$PROJECT_DIR/env/etc \
-        ENV_DIR=$PROJECT_DIR/env \
-        PROJECT_ENV=$([[ -f $PROJECT_DIR/env/etc/environment ]] && cat $PROJECT_DIR/env/etc/environment || echo 'dev') \
-        BIN_DIR=$PROJECT_DIR/env/bin \
-        RUN_DIR=$PROJECT_DIR/env/run \
-        LOG_DIR=$PROJECT_DIR/env/log \
-        VAR_DIR=$PROJECT_DIR/env/var \
-        TMP_DIR=$PROJECT_DIR/env/tmp \
-        KISS_CORE=$PROJECT_DIR/app/core.php \
-        HTTP_HOST=$(hostname) \
-        PATH=$PROJECT_DIR:$PROJECT_DIR/env/bin:$path_backup \
-        PS1=$PS1 \
-        bash
-
-        [[ ! -z $ci_pid ]] && kill $ci_pid
-        cd $oldpath
-      else
-
-        export PROJECT=$name
-        export PROJECT_DIR=$HOME/$PROJECT
-        export APP_DIR=$PROJECT_DIR/app \
-          HTML_DIR=$PROJECT_DIR/html \
-          CONFIG_DIR=$PROJECT_DIR/env/etc \
-          ENV_DIR=$PROJECT_DIR/env \
-          PROJECT_ENV=$([[ -f $PROJECT_DIR/env/etc/environment ]] && cat $PROJECT_DIR/env/etc/environment || echo 'dev') \
-          BIN_DIR=$PROJECT_DIR/env/bin \
-          RUN_DIR=$PROJECT_DIR/env/run \
-          LOG_DIR=$PROJECT_DIR/env/log \
-          VAR_DIR=$PROJECT_DIR/env/var \
-          TMP_DIR=$PROJECT_DIR/env/tmp \
-          KISS_CORE=$PROJECT_DIR/app/core.php \
-          HTTP_HOST=$(hostname) \
-          PATH=$PROJECT_DIR:$PROJECT_DIR/env/bin:$path_backup
-        cd $PROJECT_DIR
-      fi
-    else
-      echo "The project $name was not found."
-    fi
-  else
+  if [[ -z "$1" ]]; then
     echo "Usage: kiss PROJECT"
+    exit 1
   fi
+
+  name=`basename $1`
+  if [[ ! -d "$HOME/$name" ]]; then
+    echo "The project $name was not found."
+    exit 1
+  fi
+
+  if [[ "$bash_interactive" ]]; then
+    if [[ "$PROJECT" == "$name" ]]; then
+      echo "Error: already in $PROJECT..."
+      exit 1
+    fi
+
+    oldpath=`pwd`
+    cd $HOME/$name
+    ci_pid=$!
+
+    PROJECT=$name \
+    PROJECT_DIR=$HOME/$PROJECT \
+    APP_DIR=$PROJECT_DIR/app \
+    HTML_DIR=$PROJECT_DIR/html \
+    CONFIG_DIR=$PROJECT_DIR/env/etc \
+    ENV_DIR=$PROJECT_DIR/env \
+    PROJECT_ENV=$([[ -f $PROJECT_DIR/env/etc/environment ]] && cat $PROJECT_DIR/env/etc/environment || echo 'dev') \
+    BIN_DIR=$PROJECT_DIR/env/bin \
+    RUN_DIR=$PROJECT_DIR/env/run \
+    LOG_DIR=$PROJECT_DIR/env/log \
+    VAR_DIR=$PROJECT_DIR/env/var \
+    TMP_DIR=$PROJECT_DIR/env/tmp \
+    KISS_CORE=$PROJECT_DIR/app/core.php \
+    HTTP_HOST=$(hostname) \
+    PATH=$PROJECT_DIR:$PROJECT_DIR/env/bin:$path_backup \
+    PS1=$PS1 \
+    bash
+
+    [[ ! -z $ci_pid ]] && kill $ci_pid
+    cd $oldpath
+  else
+
+    export PROJECT=$name
+    export PROJECT_DIR=$HOME/$PROJECT
+    export APP_DIR=$PROJECT_DIR/app \
+      HTML_DIR=$PROJECT_DIR/html \
+      CONFIG_DIR=$PROJECT_DIR/env/etc \
+      ENV_DIR=$PROJECT_DIR/env \
+      PROJECT_ENV=$([[ -f $PROJECT_DIR/env/etc/environment ]] && cat $PROJECT_DIR/env/etc/environment || echo 'dev') \
+      BIN_DIR=$PROJECT_DIR/env/bin \
+      RUN_DIR=$PROJECT_DIR/env/run \
+      LOG_DIR=$PROJECT_DIR/env/log \
+      VAR_DIR=$PROJECT_DIR/env/var \
+      TMP_DIR=$PROJECT_DIR/env/tmp \
+      KISS_CORE=$PROJECT_DIR/app/core.php \
+      HTTP_HOST=$(hostname) \
+      PATH=$PROJECT_DIR:$PROJECT_DIR/env/bin:$path_backup
+    cd $PROJECT_DIR
+  fi
+
 fi
